name: CI

on:
  push:
    branches:
      - master
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout job
      uses: actions/checkout@v4

    - name: Welcome MR.
      run: echo "Mohammad Dada Khalandar"

    - name: Shell Command
      run: |
        echo "Hi Mohammad"
        mkdir ABCD && cd ABCD
        pwd
        touch f1.txt
        ls -al
        top
        df -sh
        
      
